---
repos:
  - repo: local
    hooks:
      - id: fix
        name: fix
        entry: bash -c 'pipenv run pre-commit-fix'
        language: system
      - id: format
        name: format
        entry: bash -c 'pipenv run pre-commit-format'
        language: system
      - id: stylecheck
        name: stylecheck
        entry: bash -c 'pipenv run stylecheck'
        language: system
      - id: typecheck
        name: typecheck
        entry: bash -c 'pipenv run typecheck'
        language: system
        verbose: true
      - id: test
        name: test
        entry: bash -c 'pipenv run test'
        language: system
      - id: test coverage
        name: test coverage
        entry: bash -c 'pipenv run test-coverage'
        language: system
      - id: yamllint
        name: yamllint
        entry: bash -c 'pipenv run yamllint'
        language: system