---
services:
  app:
    build:
      context: .
    container_name: transcriber
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    command: pipenv run transcribe --model=medium ./data/audio ./data/transcription # yamllint disable-line rule:line-length
